### ISSUE TITLE
Browser does not update

### ISSUE THREAD

**Issue by eupiteco** [osp/osp.tools.html2print#1]
Hello! Great project you people are building!

The issue is the browser does not display any changes to less, js or html files when I refresh the localhost page. I've modified the content of `setup.js`, `setup.less` and `content.html` but the pages won't get updated with the changes. 
Even re-launching the server does not do it.

I'm running the html2print under Firefox 54 and Ubuntu 16.04

**Comment by aleray** [comment]
Hi Piteco,

could you try to force-fresh (shift + reload)? And maybe clear the cache of your browser (or try the private navigation mode)?

The version shipped with this repository is pretty old, and we are about to make a new release that simplifies a lot the usage. It should happen in the comming days.

Thanks
